"""Initial migration

Revision ID: 69633396ae9b
Revises: 
Create Date: 2024-03-19 14:12:12.351733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69633396ae9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('to_do_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=5000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do_note')
    op.drop_table('user')
    # ### end Alembic commands ###
